apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shopping-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: philthygpt/backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DB_HOST
          value: "shoppingdb"
        - name: DB_USER
          value: "hse24"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "shoppingdb"