apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: shopping-app-namespace
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: backend
  type: ClusterIP  # Nur intern verfügbar