apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: shopping-app-namespace
spec:

  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081 
  selector:
    app: frontend
  type: NodePort