apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: shopping-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: philthygpt/frontend:latest
        ports:
        - containerPort: 5000
        env:
        - name: BACKEND_URL
          value: "http://backend:8080"