apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingdb
  namespace: shopping-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingdb
  template:
    metadata:
      labels:
        app: shoppingdb
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "hse24"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "shoppingdb"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        emptyDir: {}